### PR TITLE
Feature: Add cypress

### PR DESCRIPTION
**Pull request by AlfMa**
Adding cypress image to be used later on.
Nothing else should change.

### CODE REVIEW

**Comment by cdcline** [comment]
CR 👍

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :fish: through bb5f7a4

**Comment by deltuh-vee** [comment]
@AlfMa Do you have any QA notes for this?

**Comment by AlfMa** [comment]
> @AlfMa Do you have any QA notes for this? Is it enough to spin up a docker container and check that Cypress is there?

It would be enough to just check it out and run `make up` as this should start the container. 
With `make shell` you can access the shell within the container itself.

**Comment by deltuh-vee** [comment]
QA 🎬 
`make up` spun up a docker container with cypress/base:12 as the image.

**Pull request merged**
