### PR TITLE
Local dev: Fix it!

### PR DESCRIPTION
**Pull request by danielbeardsley**
Mostly mess with the Makefile to get the tasks working repeatably.

Now it should be:
```
make install
vim data/shopify-v2/.env
make start
```

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA should be follow the directions and see if you get a working local dev environment. I'll happily walk through this with someone.

**Comment by evannoronha** [comment]
Does the README need to be updated as well?

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 01e3217
Looks clean! @evannoronha has a good point; deploy_block :+1: on that.

**Review by evannoronha — CHANGES_REQUESTED** [review]
CR 🔥 

Add some usage instructions to the readme please! dev_block 🔥

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through 72936f7

**Comment by andyg0808** [comment]
un_deploy_block :+1: 
Docs updated!

**Review by evannoronha — APPROVED** [review]
CR 🔥

**Comment by deltuh-vee** [comment]
QA 🎬 
I was able to get local dev setup and running.

**Pull request merged**
